[package]
authors = ["Wesley Parr <rustchain64@gmail.com>"]
edition = "2018"
name = "db_connect"
version = "0.1.0"

[dependencies]
nng = ""
rand = "0.8.3"
sqlx = {version = "0.5", features = ["runtime-tokio-rustls", "postgres"]}
tokio = {version = "1", features = ["full"]}
