[package]
authors = ["Wesley Parr <rustchain64@gmail.com>"]
edition = "2018"
name = "db_connect"
version = "0.1.0"

[dependencies]
async-std = {version = "1.6", features = ["attributes"]}
nng = ""
rand = "0.8.3"
sqlx = {version = "0.5", features = ["runtime-async-std-native-tls", "postgres"]}
